project:
  type: website

website:
  title: "Professor McQuaid"
  page-footer:
    center: "Copyright 2023, Bob McQuaid"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Simulation"
        file: simulation.qmd
      - text: "Optimization"
        file: optimization.qmd
      - text: "Advanced Statistics"
        file: advancedstats.qmd
      - about.qmd

  sidebar:
    - title: "Simulation"
      style: "floating"
      contents:
        - simulation.qmd
        - sim2.qmd
    - title: "Optimization"
      contents:
      - optimization.qmd
    - title: "Advanced Statistics"
      contents:
        - advancedstats.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

